### ISSUE TITLE
LCOM4.xsl:60-61: LCOM4: need to finish implementing the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#216]
The puzzle `8-435f2b33` from #8 has to be resolved:

https://github.com/yegor256/jpeek/blob/26b20a9501bca68cd1a9b99fbceec3e485dfd22e/src/main/resources/org/jpeek/metrics/LCOM4.xsl#L60-L61

The puzzle was created by rultor on 26-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#216](https://github.com/yegor256/jpeek/issues/216) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#216](https://github.com/yegor256/jpeek/issues/216) assigned to @verkhovin[/z](https://www.0crat.com/u/verkhovin), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/39e98635-7bbd-4c3d-aee1-383f21939ac2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The user @verkhovin[/z](https://www.0crat.com/u/verkhovin) resigned from [#216](https://github.com/yegor256/jpeek/issues/216), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @verkhovin[/z](https://www.0crat.com/u/verkhovin)

**Comment by verkhovin** [comment]
@yegor256 my PR for this issue is waiting for review for 8 days. Assign this issue back to me, if you can.
In any case, watch at the [pr](https://github.com/yegor256/jpeek/pull/278), there is nobody in the REV role for the issue

**Comment by verkhovin** [comment]
@paulodamaso as you are a new architect, my last comment(https://github.com/yegor256/jpeek/issues/216#issuecomment-445936195) is addressed to you. Please, pay attention

**Comment by 0pdd** [comment]
The puzzle `8-435f2b33` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#294](https://github.com/yegor256/jpeek/issues/294), [#295](https://github.com/yegor256/jpeek/issues/295) are still not solved.

**Comment by 0crat** [comment]
The job [#216](https://github.com/yegor256/jpeek/issues/216) is now out of scope

**Comment by 0pdd** [comment]
@0pdd the puzzle [#295](https://github.com/yegor256/jpeek/issues/295) is still not solved; solved: [#294](https://github.com/yegor256/jpeek/issues/294).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#497](https://github.com/cqfn/jpeek/issues/497) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#578](https://github.com/cqfn/jpeek/issues/578) is still not solved; solved: [#497](https://github.com/cqfn/jpeek/issues/497).
