### ISSUE TITLE
XmlGraph.java:71-74: Nodes connections are built based on...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#413]
The puzzle `408-56dd88a6` from #408 has to be resolved: 

https://github.com/yegor256/jpeek/blob/e76abc933c9a2e4ed9e700b78ffe98bd865c978f/src/main/java/org/jpeek/graph/XmlGraph.java#L71-L74

The puzzle was created by Hamdi Douss on 05-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#413](https://github.com/yegor256/jpeek/issues/413) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/ce6e02a6-08fe-4aeb-8070-fcde54c309b2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by HDouss** [comment]
@paulodamaso Please see #403 this is clearly an impediment

**Comment by HDouss** [comment]
@0crat wait for #403

**Comment by paulodamaso** [comment]
@HDouss #403 is solved, please go on

**Comment by 0pdd** [comment]
The puzzle `408-56dd88a6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/jpeek/issues/413#issuecomment-610356203))

@sereshqua There is no quality review for [#413](https://github.com/yegor256/jpeek/issues/413), no performer

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445) are still not solved; solved: [#440](https://github.com/yegor256/jpeek/issues/440).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#441](https://github.com/yegor256/jpeek/issues/441), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459) are still not solved; solved: [#440](https://github.com/yegor256/jpeek/issues/440), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#441](https://github.com/yegor256/jpeek/issues/441), [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473) are still not solved; solved: [#440](https://github.com/yegor256/jpeek/issues/440), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459).

**Comment by vzurauskas** [comment]
@0crat wait for https://github.com/yegor256/jpeek/pull/479

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/jpeek/pull/479 ([here](https://github.com/yegor256/jpeek/issues/413#issuecomment-639701558))

@vzurauskas Job `gh:yegor256/jpeek#413` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd the puzzle [#473](https://github.com/yegor256/jpeek/issues/473) is still not solved; solved: [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459), [#472](https://github.com/yegor256/jpeek/issues/472).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#484](https://github.com/yegor256/jpeek/issues/484) is still not solved; solved: [#440](https://github.com/yegor256/jpeek/issues/440), [#441](https://github.com/yegor256/jpeek/issues/441), [#443](https://github.com/yegor256/jpeek/issues/443), [#444](https://github.com/yegor256/jpeek/issues/444), [#445](https://github.com/yegor256/jpeek/issues/445), [#459](https://github.com/yegor256/jpeek/issues/459), [#472](https://github.com/yegor256/jpeek/issues/472), [#473](https://github.com/yegor256/jpeek/issues/473).
